import Foundation
import BrowserTrafficControlCore

let router = URLRouter()
let ordered = Settings(rules: [Rule(pattern: "https://github.com/company/**", profile: "Work"), Rule(pattern: "https://github.com/**", profile: "GitHub")])
precondition(router.profile(for: URL(string: "https://github.com/company/repo")!, settings: ordered) == "Work")
precondition(router.wildcard("https://*.example.com/**", "https://docs.example.com/a/b"))
precondition(router.wildcard("https://example.com/projects/*", "https://example.com/projects/alpha"))
precondition(!router.wildcard("https://example.com/projects/*", "https://example.com/projects/a/b"))
let fallback = Settings(rules: [Rule(pattern: "https://work.example/**", profile: "Work")])
precondition(router.profile(for: URL(string: "https://news.example.org")!, settings: fallback) == nil)
precondition(router.isValidWebURL(URL(string: "http://example.com")!))
precondition(router.isValidWebURL(URL(string: "https://example.com/path")!))
precondition(!router.isValidWebURL(URL(string: "ftp://example.com")!))
let original = Settings(rules: [Rule(pattern: "https://github.com/company/**", profile: "Work")])
let decoded = try! JSONDecoder().decode(Settings.self, from: JSONEncoder().encode(original))
precondition(decoded == original)
precondition(ProfileList.normalize("Personal, Work, Personal\n") == ["Personal", "Work"])
let edge = Settings(rules: [Rule(pattern: "HTTPS://EXAMPLE.COM:443/path?x=*", profile: "Exact"), Rule(pattern: "https://*.example.com/**", profile: "Wildcard")])
precondition(router.profile(for: URL(string: "https://example.com:443/path?x=1#frag")!, settings: edge) == "Exact")
precondition(router.profile(for: URL(string: "https://sub.example.com/a/b")!, settings: edge) == "Wildcard")
precondition(router.profile(for: URL(string: "https://not-example.com/a")!, settings: edge) == nil)
precondition(HandlerStateLogic.classify(http: true, https: true) == .configured)
precondition(HandlerStateLogic.classify(http: true, https: false) == .partial)
precondition(HandlerStateLogic.classify(http: false, https: false) == .notConfigured)
precondition(HandlerStateLogic.classify(http: nil, https: true) == .unavailable)
precondition(HandlerStateLogic.classify(http: true, https: true, eligible: false) == .staleRegistration)
precondition(LaunchIntentLogic.shouldShowConfigurationWindow(.userInterface))
precondition(!LaunchIntentLogic.shouldShowConfigurationWindow(.externalURL))
let latency = LatencySummary(samples: [4, 1, 8, 2, 10, 3, 5, 6, 7, 9])
precondition(latency.count == 10 && latency.minimum == 1 && latency.median == 6 && latency.p95 == 10 && latency.maximum == 10)
print("BrowserTrafficControlValidation: 5 checks passed")
